# DataSource Config h2数据库 文件型 不需要安装
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    #    url: jdbc:h2:mem:test
    url: jdbc:mysql://192.168.56.134:12345/temp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

logging:
  path: ../logs


